export const allGenres = [
  'big room',
  'dance pop',
  'edm',
  'electro house',
  'pop',
  'progressive electro house',
  'tropical house',
  'house',
  'minimal techno',
  'schranz',
  'tech house',
  'techno',
  'electropop',
  'indie r&b',
  'indietronica',
  'deep big room',
  'dutch house',
  'progressive house',
  'folk',
  'folk-pop',
  'lilith',
  'mellow gold',
  'new wave pop',
  'pop rock',
  'scottish new wave',
  'soft rock',
  'alternative dance',
  'australian dance',
  'filter house',
  'big beat',
  'disco house',
  'electronic',
  'new rave',
  'uk garage',
  'vocal house',
  'aussietronica',
  'indie poptimism',
  'vapor soul',
  'progressive uplifting trance',
  'uplifting trance',
  'art pop',
  'chamber pop',
  'experimental pop',
  'icelandic pop',
  'metropopolis',
  'permanent wave',
  'trip hop',
  'afro house',
  'deep house',
  'kwaito house',
  'bass trap',
  'brostep',
  'dubstep',
  'electronic trap',
  'german techno',
  'microhouse',
  'contemporary country',
  'country',
  'country road',
  'modern country rock',
  'redneck',
  'brazilian electronica',
  'deep groove house',
  'melbourne bounce',
  'tropical pop edm',
  'deep disco house',
  'deep melodic euro house',
  'minimal tech house',
  'tribal house',
  'chamber psych',
  'float house',
  'shiver pop',
  'downtempo',
  'hip hop',
  'turntablism',
  'adult standards',
  'cabaret',
  'christmas',
  'easy listening',
  'lounge',
  'swing',
  'vocal jazz',
  'catstep',
  'complextro',
  'filthstep',
  'progressive trance',
  'trance',
  'bass music',
  'future garage',
  'dance-punk',
  'electroclash',
  'neo-synthpop',
  'nu jazz',
  'nu skool breaks',
  'australian hip hop',
  'deep australian indie',
  'escape room',
  'chillwave',
  'indie psych-rock',
  'nu disco',
  'shimmer pop',
  'vaporwave',
  'wonky',
  'acid house',
  'chicago house',
  'hip house',
  'laboratorio',
  'new romantic',
  'new wave',
  'vintage french electronic',
  'deep minimal techno',
  'breakbeat',
  'hardcore techno',
  'norwegian hip hop',
  'norwegian pop',
  'vapor twitch',
  'deep tropical house',
  'ccm',
  'christian alternative rock',
  'christian music',
  'christian rock',
  'world worship',
  'worship',
  'indie pop',
  'indie rock',
  'modern rock',
  'swedish electropop',
  'swedish indie pop',
  'swedish synthpop',
  'etherpop',
  'gauze pop',
  'drum and bass',
  'liquid funk',
  'intelligent dance music',
  'ambient',
  'art rock',
  'compositional ambient',
  'dream pop',
  'drone',
  'experimental',
  'experimental rock',
  'fluxwork',
  'fourth world',
  'freak folk',
  'hauntology',
  'mandible',
  'neo-psychedelic',
  'noise pop',
  'noise rock',
  'outsider house',
  'post-rock',
  'glitch hop',
  'banda',
  'grupera',
  'norteno',
  'ranchera',
  'regional mexican',
  'dance rock',
  'europop',
  'synthpop',
  'post-teen pop',
  'strut',
  'acid techno',
  'detroit techno',
  'dub techno',
  'modern alternative rock',
  'chillstep',
  'tracestep',
  'hardstyle',
  'electro',
  'belgian indie',
  'mashup',
  'neurofunk',
  'acid jazz',
  'danish electro-pop',
  'finnish edm',
  'deep euro house',
  'vapor pop',
  'indie anthem-folk',
  'indie electro-pop',
  'viral pop',
  'indian indie',
  'pop house',
  'pop rap',
  'alternative rock',
  'garage rock',
  'rock',
  'electro swing',
  'indie dream pop',
  'country gospel',
  'country rock',
  'cowboy western',
  'nashville sound',
  'outlaw country',
  'traditional country',
  'northern irish indie',
  'latvian pop',
  'dutch hip hop',
  'dark jazz',
  'grave wave',
  'destroy techno',
  'rap',
  'underground hip hop',
  'chillhop',
  'jazz boom bap',
  'la indie',
  'stomp and holler',
  'r&b',
  'british jazz',
  'broken beat',
  'indie jazz',
  'moombahton',
  'zapstep',
  'wave',
  'candy pop',
  'scottish hip hop',
  'australian alternative rock',
  'japanese classical performance',
  'violin',
  'australian pop',
  'eurodance',
  'neo soul',
  'british contemporary classical',
  'british soundtrack',
  'soundtrack',
  'swedish pop',
  'emo rap',
  'krautrock',
  'austindie',
  'gangster rap',
  'southern hip hop',
  'trap music',
  'abstract beats',
  'arab alternative',
  'brooklyn indie',
  'dreamo',
  'french indietronica',
  'jam band',
  'pop punk',
  'alternative hip hop',
  'east coast hip hop',
  'hardcore hip hop',
  'melancholia',
  'uk contemporary r&b',
  'britpop',
  'madchester',
  'post-punk',
  'uk post-punk',
  'athens indie',
  'indie emo'
];
