const artistsByAgency = {
  WME: [
    '2MANYDJs',
    'ADAM BEYER',
    'ADAM BEYER & CIREZ D',
    'AFROJACK',
    'ALESSO',
    'ALEX FRANKEL',
    'ALOK',
    'ALUNAGEORGE',
    'ANNIE',
    'APSTER',
    'B.TRAITS',
    'BAG RAIDERS',
    'BASEMENT JAXX',
    'BAYNK',
    'BEN NICKY',
    'BENJI B',
    'BETTER LOST THAN STUPID',
    'BJORK',
    'BLACK COFFEE',
    'BLAQK AUDIO',
    'BOBBY BURNS',
    'BOOKA SHADE',
    'BORGORE',
    'CALLIE REIFF',
    'CALVIN HARRIS',
    'CHANNEL TRES',
    'CHARLOTTE DE WITTE',
    'CHASE & STATUS',
    'CHRIS LAKE',
    'CHUCKIE',
    'CID',
    'CLAPTONE',
    'CRISTOPH',
    'D-WAYNE',
    'DADDY G',
    'DAMIAN LAZARUS',
    'DANIEL AVERY',
    'DEADMAU5',
    'DEORRO',
    'DESPACIO',
    'DISCIPLES',
    'DJ SHADOW',
    'DJ SNOOPADELIC',
    'DON DIABLO',
    'DURANTE',
    'EMMIT FENN',
    'ERA ISTREFI',
    'ERIC PRYDZ',
    'EROL ALKAN',
    'FATBOY SLIM',
    'FEED ME',
    'FELIX JAEHN',
    'FRANK WALKER',
    'GALANTIS',
    'GARETH EMERY',
    'GAVIN RAYNA RUSSOM',
    'GEORGE FITZGERALD',
    'GLOWIE',
    'GOLDFRAPP',
    'GROOVE ARMADA',
    'GUY GERBER',
    'HERMITUDE',
    'HITCHHIKER',
    'HOLY GHOST!',
    'HOT SINCE 82',
    'ICARUS',
    'IDRIS ELBA',
    'IGLOOGHOST',
    'JACK NOVAK',
    'JACKMASTER',
    'JACQUES LU CONT',
    'JAMES MURPHY',
    'JAY HARDWAY',
    'JEAN MICHEL JARRE',
    'JORIS VOORN',
    'JOSEPH CAPRIATI',
    'JUSTICE',
    'KAP SLAP',
    'KAYZO',
    'KIDSWASTE',
    'KOLSCH',
    'KYGO',
    'LEFTFIELD',
    'LEROY STYLES',
    'LIDO',
    'LOODS',
    'LOST KINGS',
    'LOUD LUXURY',
    'M.I.A.',
    'MADEON',
    'MAKO',
    'MALAA',
    'MARTIN BUTTRICH',
    'MARTIN GARRIX',
    'MARVIN HUMES',
    'MASSIVE ATTACK',
    'MATTHEW KOMA',
    'MAYA JANE COLES',
    'MIA',
    'MICHAEL BRUN',
    'MICHAEL SMITH',
    'MIDNIGHT KIDS',
    'MIIKE SNOW',
    'MURDA BEATZ',
    'MUSEUM OF LOVE',
    'NAATIONS',
    'NERO',
    'NERVO',
    'NETSKY',
    'NO MANA',
    'NOLIFE',
    'ONEOHTRIX POINT NEVER',
    'ORBITAL',
    'PANDA FUNK',
    'PAPER DIAMOND',
    'PARIS HILTON',
    'PAZ',
    'PEGGY GOU',
    'PET SHOP BOYS',
    'PETE TONG',
    'PLASTIKMAN',
    'PLAYMODE',
    'PORTER ROBINSON',
    'PUNCTUAL',
    'RICHIE HAWTIN',
    'ROBERT DELONG',
    'SAM FELDT',
    'SASHA GREY',
    'SAVOY',
    'SCUBA',
    'SETH TROXLER',
    'SG LEWIS',
    'SHOWTEK',
    'SHPONGLE (SIMON POSFORD DJ SET)',
    'SKRILLEX',
    'SOULWAX',
    'SPOR',
    'ST. LUCIA',
    'STEVE AOKI',
    'SWINDAIL',
    'TESTPILOT',
    'THE ASTON SHUFFLE',
    'THE AVALANCHES',
    'THE CHEMICAL BROTHERS',
    'THE HIM',
    'THE MARTINEZ BROTHERS',
    'THIEVERY CORPORATION',
    'THOMAS JACK',
    'THRD L!FE',
    'TIGA',
    'TRENTEMOLLER',
    'TRIPPY TURTLE',
    'UNDERWORLD',
    'VIRGIL ABLOH',
    'VIRTUAL SELF',
    'WILLARIS. K',
    'WOODEN WISDOM: ELIJAH WOOD & ZACH COWIE',
    'YOSHI FLOWER',
    'YOTTO',
    'YOUNG BOMBS',
    'ZANE LOWE',
    'ZEDD',
    'ZEN FREEMAN',
    'ZHU'
  ],
  CAA: [
    '3LAU',
    'APRE',
    'Air',
    'Alex Adair',
    'Alex Ross',
    'Alex Winston',
    'Ali Love',
    'All Day I Dream',
    'Alle Farben',
    'Anabel Englund',
    'Andreas Moss',
    'Anna of the North',
    'Anohni',
    'Anton Powers',
    'Arctic Lake',
    'Art Vs. Science',
    'Astrid S',
    'Atoms for Peace',
    'Autograf',
    'Bailo',
    'Becky Hill',
    'Bedouin',
    'Bella Thorne',
    'Ben Phipps',
    'Black Eyed Peas',
    'Bloc Party',
    'Booka Shade',
    'Brasstracks',
    'Brody Jenner',
    'CADE',
    'CVBZ',
    'Cameron A G',
    'Capital Cities',
    'Captain Cuts',
    'Caravan Palace',
    'Cedric Gervais',
    'Cheat Codes',
    'Christine and the Queens',
    'Chromeo',
    'Client Liaison',
    'Conway',
    'Cosha',
    "Cosmo's Midnight",
    'Crystal Fighters',
    'DJ Falcon',
    'DJ Sam Spiegel',
    'DJ Windows 98',
    'DJ Z-Trip',
    'Daft Punk',
    'Dakota',
    'DallasK',
    'Darren King',
    'David Guetta',
    'Deepend',
    'Demo Taped',
    'Dena Amy',
    'Desert Hearts',
    'Detlef',
    'Detox Unit',
    'Digital Farm Animals',
    'Dimitri Vegas & Like Mike',
    'Dr. Fresch',
    'Dub Fx',
    'Elderbrook',
    'Elephante',
    'Eliot Sumner',
    'Exmag',
    'Far East Movement',
    'Feder',
    'Flight Facilities',
    'Fono',
    'Forest Swords',
    'Francis and the Lights',
    'G Jones',
    'GRIZ',
    'Galcher Lustwerk',
    'Galimatias',
    'Gavin Turek',
    'Gesaffelstein',
    'Gianluca Vacchi',
    'Glass Animals',
    'Glenn Morrison',
    'GoldLink',
    'Goldroom',
    'Gramatik',
    'Grandtheft',
    'Grouplove',
    'HER',
    'Hayden James',
    'Henry Wu',
    'Hercules & Love Affair',
    'Hernan Cattaneo',
    'Herobust',
    'Holy F*ck',
    'Holy Ghost!',
    'Hot Creations',
    'Hucci',
    'Hudson Mohawke',
    'Hugel',
    'IHF',
    'IO Echo',
    'Icona Pop',
    'Jack Garratt',
    'Jade Cicada',
    'Jadu Heart',
    'Jagwar Ma',
    'Jamie Jones',
    'Janelle Kroll',
    'Jenaux',
    'Jerome Price',
    'Joe Jonas',
    'John Martin',
    'John Splithoff',
    'Jonas Blue',
    'Jonny Greenwood',
    'Justin Caruso',
    'KAMIO',
    'KDA',
    'KRANE',
    'Kaleida',
    'Karnaval Blues',
    'Kasbo',
    'Kiah Victoria',
    'Kidnap',
    'Klingande',
    'Kraddy',
    'Kraftwerk',
    'Kungs',
    'Kylie Minogue',
    'Lana Del Rey',
    'Lauren Lane',
    'Lee Burridge',
    'Lee Foss',
    'Little Dragon',
    'Lo Down Loretta Brown',
    'Lo Moon',
    'Loosid',
    'Lost Frequencies',
    'Lykke Li',
    'MALLRAT',
    'MONKI',
    'MSTRKRFT',
    'Mansionz',
    'Mark Hoppus',
    'Mark Ronson',
    'Markus Schulz',
    'Mashrou’ Leila',
    'Matt DiMona',
    'Max Frost',
    'MiM0SA',
    'Michal Menert',
    'Mike WiLL Made-It',
    'Mikey Lion',
    'Mo Kolours',
    'Monolink',
    'Monte Booker',
    'Moses Boyd',
    'Motez',
    'Mutemath',
    'Myles Hendrik',
    'N.A.S.A.',
    'Nathan Barato',
    'Natureboy Flako',
    'Naughty Boy',
    'New Order',
    'New World Punx',
    'Nicky Romero',
    'Noodles',
    'Oberhofer',
    'Oliver Heldens',
    'Osunlade',
    'Otzeki',
    'Owl City',
    'PREP',
    'Paradise',
    'Patrick Baker',
    'Paul Kalkbrenner',
    'Pretty Lights',
    'Purple Disco Machine',
    'Q-Tip',
    'RAC',
    'Radiohead',
    'Rebel and a Basketcase',
    'Ricky Reed',
    'Rob da Bank',
    'Robert DeLong',
    'Robin Schulz',
    'Roisin Murphy',
    'Roosevelt',
    'RÜFÜS DU SOL',
    'SNBRN',
    'STS9',
    'Sam Gellaitry',
    'Scott Quinn',
    'Sebu of Capital Cities DJ set',
    'Seramic',
    'Sevdaliza',
    'Shaun Frank',
    'Silk City',
    'Sir Rosevelt',
    'Smallpools',
    'Starling',
    'StayLoose (fka STéLOUSE)',
    'Super Duper',
    'SuperVision',
    'Swell',
    'TJR',
    'Tears For Fears',
    'Tei Shi',
    'Tensnake',
    'Tep No',
    'The Big Pink',
    'The Chainsmokers',
    'The Cure',
    'The Naked and Famous',
    'The Righteous Young',
    'The Sounds',
    'Thom Yorke',
    'Tipper',
    'Tom Misch',
    'Travis Barker',
    'Tunji Ige',
    'Twenty One Pilots',
    'Two Door Cinema Club',
    'TÂCHES',
    'Uncle Jxm',
    'Vancouver Sleep Clinic',
    'Vice',
    'Vicetone',
    'Wet',
    'White Cliffs',
    'Will Heard',
    'Winston Surfshirt',
    'Yuma X',
    'Zac Samuel',
    'Zak Abel',
    'Zero 7',
    '††† (CROSSES)'
  ],
  UTA: [
    '10 Years',
    '17 Memphis',
    '1991',
    '21 Savage',
    '2CELLOS',
    '3 Doors Down',
    '36 Crazy Fists',
    '808 State',
    '99 Souls',
    'A Boogie wit da Hoodie',
    'A Bowie Celebration',
    'A Day To Remember',
    'A Dead Forest Index',
    'A Great Big Pile of Leaves',
    'A Great Big World',
    'A Night With Janis Joplin',
    'A Will Away',
    'Aaron Gillespie',
    'Aaron Lewis',
    'Aaron Tippin',
    'Aaron West and The Roaring Twenties',
    'The Aces',
    'Action Bronson',
    'Adam Ant',
    'Adam Deitch',
    'Adventure Club',
    'Aero Flynn',
    'Aesop Rock',
    'AFK',
    'Against Me!',
    'Against the Current',
    'Agar Agar',
    'Airways',
    'AJ Brown',
    'AJ Tracey',
    'Aja9',
    'Akon',
    'Al Ross',
    'Aled Jones',
    'Aleem',
    'Alex Vargas',
    'Alexis Ffrench',
    'Alexisonfire',
    'Alfie Boe',
    'Alice Cooper',
    'Alice Russell',
    'Alissia',
    'Alix Perez',
    'All Our Exes Live in Texas',
    'All Them Witches',
    'All Tvvins',
    'Allah-Las',
    'Allan Rayman',
    'Alter Bridge',
    'Amanda Palmer',
    'Amanda Tenfjord',
    'Amara La Negra',
    'Amelia Lily',
    'American Fangs',
    'American Young',
    'Amerigo Gazaway',
    'Amine Edge & DANCE',
    'Amir Obe',
    'The Amity Affliction',
    'Analog Son',
    'Andre Power',
    'Andrew Lloyd Webber Presents: A Lifetime of Memories and Gre',
    "Andrew O'Neill",
    'Andrew Watt',
    'Andreya Triana',
    'Andy Black',
    'Andy C',
    'Angèle',
    'Animals As Leaders',
    'Anna Faris is Unqualified',
    'Anna Meredith',
    'Anthony Green',
    'ANTI-FLAG',
    'Apashe',
    'Apocalyptica',
    'Architects',
    'Ariel Pink',
    'Arin Ray',
    'ARIUS',
    'A R I Z O N A',
    'Arkells',
    'ARMNHMR',
    'Art Garfunkel',
    'Artful',
    'Artful Dodger',
    'As It Is',
    'Asaf Avidan',
    'Asher Roth',
    'Ashley Campbell',
    'Asia',
    'Asian Doll',
    'Asking Alexandria',
    'Askjell',
    'At The Gates',
    'Attila',
    'August Burns Red',
    'AURORA',
    'The Australian Pink Floyd Show',
    'Autumn In June',
    'Avatar',
    'Aweminus',
    'Axewound',
    'Azekel',
    'Azusena',
    'B*witched',
    'BABYMETAL',
    'Bad Brains',
    'Bad Omens',
    'Bad Suns',
    'BADBADNOTGOOD',
    'Badflower',
    'BadKlaat',
    'B.A.G. (Blimes x Gab)',
    'Ball Park Music',
    'BASECAMP',
    'Basement',
    'Basia Bulat',
    'Bassjackers',
    'Bear Grillz',
    'Bear Hands',
    'Bearcubs',
    'Beartooth',
    'Beau Dermott',
    'Bedouin Soundclash',
    'Being As An Ocean',
    'Belako',
    'Bell Biv DeVoe',
    'Ben Forster',
    'Ben Haggard',
    'Benin City',
    'Benjamin Clementine',
    'Benjamin Francis Leftwich',
    'Benji Lewis',
    'Beoga',
    'Bernie Williams',
    'Bessie Turner',
    'Between The Buried And Me',
    'Big Boi',
    'Big Freedia',
    'Big Jesus',
    'Bikini Trill',
    'Bill Evans Band',
    'Bill Laurance',
    'Bill Nye',
    'Billy Bob Thornton and the Boxmasters',
    'Billy Ocean',
    'Billy Talent',
    'Bitch Falcon',
    'The Black Dahlia Murder',
    'Black Foxxes',
    'Black Label Society',
    'Black Lungs',
    'Black Moth',
    'Black Peaks',
    'The Black Seeds',
    'Black Sun Empire',
    'Black Tiger Sex Machine',
    'Black Veil Brides',
    'Black Violin',
    'BlackGummy',
    'Blake',
    'Blanco White',
    'Blanket',
    'Bleep Bloop',
    'blessthefall',
    'The Blood Brothers',
    'BLU J',
    'Blunts & Blondes',
    'Bobby Bazini',
    'Bobby Raps',
    'Bobii Lewis',
    'Bombay Bicycle Club',
    'Bonnie Prince Billy',
    'BONNIE X CLYDE',
    'Bonobo',
    'Boo Seeka',
    'Boogie Nights',
    'Boogie T',
    'Boombox Cartel',
    'BORGEOUS',
    'Born Dirty',
    'Born Of Osiris',
    'Bosco',
    'Boston Manor',
    'Boxed In',
    'BOY',
    'The Boy Least Likely to',
    'Braid',
    'The Brand New Heavies',
    'Brasstracks',
    'Break',
    'Break Science',
    'Breakbot',
    'Breathe Carolina',
    'Brent Cowles',
    'Brian Fallon & The Crowes',
    'Brian Wilson',
    'Brian Wilson (w/ special guest Al Jardine) – 50th Annivers',
    'Bridgit Mendler',
    'Bring It North',
    'Bring Me The Horizon',
    'Britpop Brass',
    'Bro Safari',
    'Broadside',
    'The Bronx/Mariachi El Bronx',
    'Brother Ali',
    'Bruce Willis & The Bruce Willis Blues Band',
    'Buffalo Tom',
    'Buku',
    'Bullet For My Valentine',
    'Bülow',
    'Burna Boy',
    'Bury Tomorrow',
    'Bush',
    'Butthole Surfers',
    'Cage The Elephant',
    'Calyx & Teebee',
    'Cameron Bloomfield',
    'Camo & Krooked',
    'Candi Staton',
    'Cannibal Corpse',
    'Caravan Palace',
    'Carla Bruni',
    'Caro Emerald',
    'Carpenter Brut',
    'Carter Winter',
    'Caspa',
    'Cassia',
    'The Cat Empire',
    'Caveman',
    'CC Smugglers',
    'Cedric Gervais',
    'Cesqeaux',
    'Ceu',
    'Chad Brownlee',
    'Chaka Khan',
    'Chapel',
    'Charlie Winston',
    'Charly Bliss',
    'Chase Atlantic',
    'Chastity Belt',
    'Chelsea Grin',
    'Chelsea Wolfe',
    'Cher Lloyd',
    'Children of Bodom',
    'Chinah',
    'Chris Bandi',
    'Chris Blue',
    'Chris Bourne',
    'Chris Difford',
    'Chris McClenney',
    'Christian Scott',
    'Christine and the Queens',
    'Christopher Cross',
    'Chrome Sparks',
    'Chuck Ragan',
    'Church of the Cosmic Skull',
    'Circa Survive',
    'Circoloco',
    'Citizen',
    'City and Colour',
    'CKY',
    'Clara Mae',
    'The Clarks',
    'Clay Walker',
    'cleopatrick',
    'Clint Black',
    'Clutch',
    'Coach Ken Carter',
    'Cobi',
    'Coeur De Pirate',
    'Cold Cave',
    'Cold Creek County',
    'Cole Plante',
    'Colin Macleod',
    'Collabro',
    'Collin Raye',
    'Colt Ford',
    'Common',
    'Confederate Railroad',
    'Conjurer',
    'Conor Maynard',
    'Conrad Sewell',
    'The Contortionist',
    'Cookie Monsta',
    'Coone',
    'Corey Smith',
    'Cornelius',
    'The Coronas',
    'Corrosion of Conformity',
    'Cory Henry & The Funk Apostles',
    'Counterparts',
    'Coven',
    'Cradle of Filth',
    'Craig Campbell',
    'Craig David',
    'Craig Morgan',
    'Crayon',
    'Creed',
    'Creeper',
    'Creo',
    'Crime In Stereo',
    'Cristin Milioti',
    'Crizzly',
    'Crowbar',
    'Crown The Empire',
    'Crystal Fighters',
    'Cub Sport',
    'Culture Abuse',
    'Cut Copy',
    'Cynthia Erivo',
    'Cypress Hill',
    'Dabin',
    'Daddy Issues',
    'Daecolm',
    'DAGNY',
    'Daily Bread',
    'Dallas Smith',
    'Dance Gavin Dance',
    'Dancing On Tables',
    'Dangerkids',
    'Daniel Johnston',
    'Daniela Andrade',
    'Danko Jones',
    'Danny T',
    'Danzig',
    'Darci',
    'Darnell Williams',
    'Darren Styles',
    'Dasco',
    'Dave Hause',
    'Dave Navarro',
    'David Clayton-Thomas',
    'David Garibaldi',
    'David Gilmour',
    'David Sylvian',
    'Davie',
    'Davisson Brothers Band',
    'Daye Jack',
    'Dayshell',
    'De La Ghetto',
    'De Lux',
    'Dead Kennedys',
    'Dean Brody',
    'Dee Dee Bridgewater',
    'Deep Purple',
    'Delta Heavy',
    'Delta Riggs',
    'Demob Happy',
    'Demon Hunter',
    'Denzel Curry',
    'dePresno',
    'Derek Hough',
    'Derin Falana',
    'Desiigner',
    'Dessa',
    'The Devil Wears Prada',
    'Devin Townsend',
    'Die Antwoord',
    'Dieselboy',
    'Dillon Cooper',
    'Dimension',
    'Dinos Chapman',
    'Dion Timmer',
    'Dionne Bromfield',
    'Dirt Monkey',
    'The Dirty Heads',
    'Dirtyphonics',
    'Disco Classical',
    'Dispatch',
    'DJ Cassidy',
    'DJ Drama',
    'DJ Khaled',
    'DJ Licious',
    'DJ Premier',
    'DJ S.K.T',
    'DJ Statik Selektah',
    'DNMO',
    'Doctor P',
    'Dolly Parton',
    'Don Broco',
    'Don Felder',
    'DonMonique',
    'Donna Missal',
    'Doomtree',
    'Dotcom',
    'Doves',
    'Downlink',
    'Dr Vades',
    'DragonForce',
    'Dream State',
    'Dredg',
    'Dresden Dolls',
    'Droeloe',
    'Drug Church',
    'dubé',
    'Dubloadz',
    'Ducky',
    'Dumblonde',
    'DUSKUS',
    'Dwight Yoakam',
    'DZ Deathrays',
    'The Early November',
    'Earthless',
    'Easy Star All-Stars',
    'Echos',
    'Ed Drewett',
    'Ed Rush',
    'The Edgar Winter Band',
    'Edwin McCain',
    'Eelke Kleijn',
    'Ego Ella May',
    'Ehide',
    'Ekali',
    'Elder Island',
    'Elena Pinderhughes',
    'Eli & Fur',
    'Elohim',
    'Ember Trio',
    'Emilie Nicolas',
    'EMP',
    'Empire of the Sun',
    'ENATION',
    'Endor',
    'The English Beat',
    'EOTO',
    'EPROM',
    'EPTIC',
    'Eric Burdon and the Animals',
    'Erick Morillo',
    'Ernest K',
    'Escala',
    'Escort',
    'Eskimo Dance',
    'ETC!ETC!',
    'Ethan Russell: The Best Seat in The House',
    'Europe',
    'Evan Dando',
    'Everlast',
    'Excision',
    'Exodus',
    'Ezra Collective',
    'Falling in Reverse',
    'Fangclub',
    'Fangs',
    'Felix Cartal',
    'Fickle Friends',
    'Fil Bo Riva',
    'Finbar Furey',
    'Findlay',
    'Fine Creatures',
    'Finn Matthews',
    'Fireball Ministry',
    'First Aid Kit',
    'Fit for a King',
    'The FIXX',
    'FLAG',
    'Fletcher',
    'Flo Morrisey',
    'Flo Rida',
    'Floor',
    'Flor',
    'Flores',
    'Flux Pavilion',
    'FM-84',
    'Foals',
    'Folly Rae',
    'FooR',
    'Foxing',
    'Frankie Rose',
    'Fransis Derelle',
    'Friction',
    'FridayAt4',
    'From Indian Lakes',
    'Fucked Up',
    'FuntCase',
    'Future Of The Left',
    'Fytch',
    'G-Eazy',
    'G.E.M.',
    'Gabriel Garzón-Montano',
    'Gad Elmaleh',
    'Galactic Empire',
    'Gammer',
    'Ganja White Night',
    'The Gaslight Anthem',
    'General Roots',
    'Gengahr',
    'Gentlemens Club',
    'Geoff Rickly',
    'George Benson',
    'George Kwali',
    'Geri Horner',
    'Ghastly',
    'The Ghost Inside',
    'Giovanni James',
    'Girl Talk',
    'Giuda',
    'Gizmo Varillas',
    'GLADES',
    'Glass Animals',
    'Gnarwolves',
    'Godflesh',
    'Godsmack',
    'Gogo Penguin',
    'Gogol Bordello',
    'Goldfish',
    'Goldie',
    'Good Charlotte',
    'Goodnight, Texas',
    'Grass Roots Revival',
    'Graveyard',
    'Greg Laswell',
    'Grizfolk',
    'Grum',
    'Gundelach',
    "Guns N' Roses",
    'Guy Sebastian',
    'GWAR',
    'GZA',
    'Hablot Brown',
    'Habstrakt',
    'Haçienda Classical',
    'Hail the Sun',
    'Halestorm',
    'Hands Like Houses',
    'Hanni El Khatib',
    'Hanson',
    'Harrison',
    'Harry Romero',
    'Hatebreed',
    'Have Mercy',
    'Hayden James',
    'He Is Legend',
    'Head Wound City',
    'The Heavytrackerz',
    'Heems',
    'Hekler',
    'Hellogoodbye',
    'Hellyeah',
    "Her's",
    'Hermitage Green',
    'Hiatus Kaiyote',
    'High Valley',
    'Highly Suspect',
    'Hilltop Hoods',
    'Hinder',
    'HINDS',
    'The Hives',
    'Holding Absence',
    'Hollie Cook',
    'Hollywood Ending',
    'Hollywood Vampires',
    'Holy Holy',
    'Honey Lung',
    'HONNE',
    'Horse Thief',
    'Hot Dub Time Machine',
    'Hot Water Music',
    'The Hotelier',
    'House of Pain',
    'HOUSSE DE RACKET',
    'Howl Ensemble',
    'Huey Mack',
    'Hundred Handed',
    'Hunny',
    'Hunter Brothers',
    'Huw Stephens',
    'I Am The Avalanche',
    'IAMSU!',
    'Ibibio Sound Machine',
    'Ibrahim Maalouf',
    'Ida Mae',
    'Idles',
    'Idolising Nova',
    'Igorrr',
    'Illenium',
    'In Flames',
    'In Hearts Wake',
    'In Real Life',
    'In This Moment',
    'Indoor Pets',
    'Infected Mushroom',
    'Infinity Ink',
    'Injury Reserve',
    'Invisible Minds',
    'IS TROPICAL',
    'Isa Chandra Moskowitz',
    'Isabella Rossellini',
    'The Isley Brothers',
    'Issues',
    'Itch',
    'J. Worra',
    'Jacob Collier',
    'Jacob Sartorius',
    'Jaden Michaels',
    'Jaguar Dreams',
    'Jake Isaac',
    'Jakubi',
    'Jalen Santoy',
    'James Graham',
    'James Hersey',
    'James Otto',
    'James Vickery',
    'Jamey Johnson',
    'Jamie Lawson',
    'Jamie Lenman',
    'Jamiroquai',
    'Jamtown',
    'Jane Birkin',
    'Jane Krakowski',
    'Jarami',
    'Jared & The Mill',
    'Jason Alexander',
    "Jason Bonham's Led Zeppelin Evening",
    'Jasta',
    'Jay Malinowski',
    'Jay Park',
    'Jayceeoh',
    'Jaykode',
    'Jazz Cartier',
    'Jazz Morley',
    'Jean Tonique',
    'Jeezy',
    'Jeff Bridges & The Abiders',
    'Jeffrey James',
    'Jeremih',
    'Jeremy Enigk',
    'Jeremy Loops',
    'Jermain Jackman',
    'Jess + Gabriel Conte',
    'Jesse & Joy',
    'Jesse Mac Cormack',
    'Jesse Malin',
    'Jesse Royal',
    'Jessica Audiffred',
    'Jessie J',
    'Jesu',
    'Jewel',
    'The Jezabels',
    'Jim Ross',
    'Jimi Goodwin',
    'Jimmie Allen',
    'Jo Mersa Marley',
    'Jody Wisternoff',
    'Joe Kay',
    'Joel Adams',
    'Joey Dosik',
    'John Anderson',
    'John Carpenter',
    'John Conlee',
    'John Gibbons',
    'John Michael Montgomery',
    'John Owen-Jones',
    'John Waters',
    'Jon Lajoie',
    'Jonathan Davis',
    'Jones',
    'Jorge Ben Jor',
    'Jorge Drexler',
    'José James',
    'Joseph J. Jones',
    'Josh Beckerman',
    'Josh Doyle',
    'Joshua Henry',
    'Jovanotti',
    'JOYRYDE',
    'JT Hodges',
    'Juan Magán',
    'Juke Ross',
    'Julianna Barwick',
    'The Julie Ruin',
    'Juliette Lewis',
    'July Talk',
    'Junior',
    'Junius Meyvant',
    'Junkie Kid',
    'Jurassic 5',
    'Jussie Smollett',
    'Just A Gent',
    'Just Kiddin',
    'Justin Nozuka',
    'K.Flay',
    'Kacy Hill',
    'Kai Wachi',
    'Kandace Springs',
    'Kari Byron',
    'Karma To Burn',
    'Kartell',
    'Kaskade',
    'Katatonia',
    'Kate Simko & London Electronic Orchestra',
    'Katey Sagal & The Reluctant Apostles',
    'Katherine Jenkins',
    'Katie Melua',
    'Keke Palmer',
    'Kelis',
    'The Kentucky Headhunters',
    'Kevin Connolly',
    'Kevin Costner & Modern West',
    'Kevin Devine',
    'Kevin Gates',
    'Kevin George',
    'Key!',
    'Kiana Ledé',
    'Kid Francescoli',
    'Killing Joke',
    'Killswitch Engage',
    'Kim Campbell',
    'Kim Russo - The Happy Medium',
    'Kim Viera',
    'King 810',
    'King Arthur',
    'The King Blues',
    'King Charles',
    'King Crimson',
    'Kingdom of Sorrow',
    'Kirk Knight',
    'Kishi Bashi',
    'KLOE',
    'The Knife',
    'Kompany',
    'Korey Dane',
    'Krimer',
    'Krokodil',
    'Krrum',
    'Krystal Keith',
    'Kyary Pamyu Pamyu',
    'Kyle Watson',
    "L'Imperatrice",
    'La Femme',
    'The Lacs',
    'Lady Bird',
    'The LaFontaines',
    'LAKIM',
    'Lamb Of God',
    'Lance Bass',
    'Lance Carpenter',
    'LANY',
    'Larkin Poe',
    'The Last Bison',
    'Laura Wright',
    'Lauren Samuels',
    'Lawrence',
    'Lawrence Curry',
    'Lawrence Rothman',
    'Le Butcherettes',
    'Le Kid',
    'Leftwing & Kody',
    'LELAND',
    'The Lemonheads',
    'Lemuria',
    'Lenny Kravitz',
    'Less Than Jake',
    "Let's Eat Grandma",
    'Lettuce',
    'Level 42',
    'Lia Marie Johnson',
    'Liam Horne',
    'Liam Prior',
    'LIFE',
    'Light the Torch',
    'Light You Up',
    'The Lightning Year',
    'LIGHTS',
    'Limp Bizkit',
    'Liquid Stranger',
    'Lisa Stansfield',
    'Liv On: Olivia Newton-John, Beth Nielsen Chapman, and Amy Sk',
    'Liza Minnelli',
    'Loadstar',
    'Logan Mize',
    'Lola Marsh',
    'London on da Track',
    'LoneLady',
    'Lonestar',
    'Lou Doillon',
    'Louis The Child',
    'Louise Distras',
    'Low Island',
    'Low Steppa',
    'Lowell',
    'LSDREAM',
    'Luca Brasi',
    'LUCA LUSH',
    'Luke Pell',
    'Lupe Fiasco',
    'Luzcid',
    'Lynyrd Skynyrd',
    'M.A.N.D.Y.',
    'M.I.L.K.',
    'MAAD',
    'Mac McAnally',
    'Madball',
    'Maddie Poppe',
    'Maddie Simpson',
    'Magnum',
    'Majestic Casual',
    'Mallory Merk',
    'Mambo Brothers',
    'Man Overboard',
    'Manchester Orchestra',
    'Mando Diao',
    "Margot & the Nuclear So and So's",
    'Mariah Carey',
    'Marianas Trench',
    'Marques Wyatt',
    'Mars Moniz',
    'Marshmello',
    'Martin Atkins',
    'Marty Grimes',
    'Marty Stuart',
    'MartyParty',
    'Marvel Years',
    'Mary Sarah',
    'Masego',
    'Massive Wagons',
    'Mat Kearney',
    'Matisyahu',
    'Matt Stell',
    'Matthew and the Atlas',
    'Matthew Herbert',
    'Matty',
    'The Mavericks',
    'Mavi Phoenix',
    'Max Raabe & Palast Orchester',
    'Maximono',
    'MCC (Magna Carta Cartel)',
    'Meat Loaf',
    'Mefjus',
    'Megalodon',
    'Melt Banana',
    'Melvv',
    'Memphis May Fire',
    'The Menzingers',
    'Metronomy',
    'mewithoutYou',
    'MF Doom',
    'MF Robots',
    'MHD',
    'Michael Bernard Fitzgerald',
    'Mick Flannery',
    'Mick Fleetwood',
    'Mick Jenkins',
    'Middle Distance',
    'Midnight Tyrannosaurus',
    'The Mighty Mighty Bosstones',
    'Miguel Migs',
    'Mike Cervello',
    'Mike Watt',
    'Mikey Mike',
    'MIKNNA',
    'Milburn',
    'Miles Mosley',
    'Milestones',
    'Milk Teeth',
    'Milky Chance',
    'Millencolin',
    'Million Dollar Quartet',
    'Million Miles’',
    'Minke',
    'Minnesota',
    'Missing Andy',
    'MitiS',
    'Moby (DJ Set)',
    'Moddi',
    'Modern Baseball',
    'MOKSI',
    'Moncrieff',
    'MoneyBagg Yo',
    'Monolord',
    'Monsieur Periné',
    'Monster Florence',
    'Monster Truck',
    'Montgomery',
    'Moonshine Bandits',
    'Moose Blood',
    'Morgan Page',
    'morgxn',
    'Mothers',
    'Motionless In White',
    'Mottron',
    'The Movielife',
    'Moxie Raia',
    'Mr Little Jeans',
    'Mr. Eazi',
    'Mr. Lif & The Perceptionists',
    'Ms. Lauryn Hill',
    'Muse',
    'MUST DIE!',
    'Mutoid Man',
    'Myles Kennedy',
    'N-Dubz',
    'N.A.S.A.',
    'Naations',
    'Nach',
    'Nai Palm',
    'Nana Adjoa',
    'Nancy and Beth',
    'Natalia Jiménez',
    'Natalie La Rose',
    'Natasha Marsh',
    'Nathan Dawe',
    'Neck Deep',
    'Ned LeDoux',
    'Negramaro',
    'Nena',
    'Neon Indian',
    'Neon Trees',
    'Nero',
    'Nessly',
    'NGHTMRE',
    'Nickelback',
    'Nicole Scherzinger',
    'Night Things',
    'Nightmares on Wax',
    'Nikita Karmen',
    'Nitin Sawhney',
    'Nitro Circus',
    'Nitti Gritti',
    'Noah Slee',
    'NOFX',
    'Noisia',
    'Northern Faces',
    'Northlane',
    'Notaker',
    'Nothing But Thieves',
    'Nouvelle Vague',
    'Now, Now',
    'NVDES',
    'O-Town',
    'Obituary',
    'Ocean Grove',
    'Of Mice & Men',
    'OFFAIAH',
    'Oi Va Voi',
    'Oleander',
    "OLIVIA O'BRIEN",
    'Olof Dreijer (The Knife)',
    'Omar LinX',
    'OMNOM',
    'One Bit',
    'One More Time - A Tribute to Daft Punk',
    'Only Boys Aloud',
    'Only The Young',
    'Ookay',
    'Opeth',
    'Optical',
    'Orange Goblin',
    'The Orb',
    'Oscar Jerome',
    'Oscar Jerome',
    'Otherwise',
    'Our Last Night',
    'Owen',
    'PAINT',
    'Palace',
    'Palace Winter',
    'Palaye Royale',
    'Pam Tillis',
    'Panda Eyes',
    'The Paper Kites',
    'Paradise Lost',
    'Paramore',
    'Parcels',
    'Park Hotel',
    'Parkway Drive',
    'Parov Stelar',
    'Party Nails',
    'Party Thieves',
    'Patina Miller',
    'Patoranking',
    'Paul Anka',
    'Paul Heyman',
    'Paul Potts',
    'Paul van Dyk',
    'Paula Abdul',
    'Paulina Rubio',
    'Peaches',
    'Peekaboo',
    'Perez Hilton – “An Evening With”',
    'Peter Frampton',
    'Peter Hook Presents Joy Division Orchestrated',
    'Petite Noir',
    'Phaeleh',
    'Phairo',
    'Phantogram',
    'Phil Campbell & The Bastard Sons',
    'The Phoenix Foundation',
    'Pia Mia',
    'Pianos Become The Teeth',
    'The Picturebooks',
    'Pierce the Veil',
    'Pink Panda',
    'Pissed Jeans',
    'PITCH: Talks On Baseball',
    'Pitou',
    'Placebo',
    'Plague Vendor',
    'Plastic Plates',
    'PNL',
    'The Pogues',
    'Poison The Well',
    'Poliça',
    'Polo & Pan',
    'Pop Evil',
    'Popof',
    'Post Malone',
    'Power Trip',
    'POWERS',
    'Preme',
    'The Presidents of USA',
    'Press To Meco',
    'PRhyme',
    'Printz Board',
    'Prok & Fitch',
    'Protoje',
    'Public Service Broadcasting',
    'Pulled Apart By Horses',
    'Pusha T',
    'Puss N Boots',
    'PVMNTS',
    'QBert',
    'Quantic',
    'Quintino',
    'Ra Ra Riot',
    'Rachel Crow',
    'Rad Horror',
    'Radwimps',
    'Raghav',
    'Raging Fyah',
    'RAHH',
    'Rajiv Dhall',
    'Real Friends',
    'Rebelution',
    'Reece',
    'Reel Big Fish',
    'Reggie Couz',
    'The Regrettes',
    'Relient K',
    'REO Speedwagon',
    '*repeat repeat',
    'The Residents',
    'Restless Heart',
    'Restorations',
    'Rexx Life Raj',
    'Rhett & Link',
    'Rich Brian',
    'Richard Rawson',
    'Richard Thompson',
    'Riles',
    'Ringo Starr',
    'Riot Ten',
    'River Oaks',
    'Riz MC',
    'Ro Shon',
    'The Road Hammers',
    'Roam',
    'Rob Halford',
    'Rob Thomas - A Special Evening Benefitting The Sidewalk Ange',
    'Robert Fripp',
    'Robin Thicke',
    'Roger Sanchez',
    'Roky Erickson',
    'Ron Artis II & Thunderstorm',
    'Royal Republic',
    'Rozwell Kid',
    'RUN DMC',
    'Running Touch',
    'Ruthie Henshall',
    'Ryan Destiny',
    'Ryan Trey',
    'Rynx',
    'Saara Aalto',
    'Saba',
    'Sacha Robotti',
    'Safia',
    'Sage Armstrong',
    'Said The Sky',
    'SAINt JHN',
    'Saint Motel',
    'Sam Frankl',
    'Sam James',
    'Sam Roberts Band',
    'Samantha Harvey',
    'Sammy Kershaw',
    'Sammy Porter',
    'SAN HOLO',
    'The Sandinistas',
    'Sandunes',
    'Santino Fontana',
    'Sara Hartman',
    'SARAH BLASKO',
    'Sarah Brightman',
    'Sash!',
    'Sasha Keable',
    'Saved By The 90s',
    'Savoir Adore',
    'Savoy',
    'Scarlet Pleasure',
    'Scarlet Pleasure',
    'Scarlet Sails',
    'Scott Blasey',
    'Seaway',
    'Sebastian Mikael',
    'Sebastien Tellier',
    'Seether',
    'Set Mo',
    'Seu Jorge',
    'Sevana',
    'Sevyn Streeter',
    'Shades',
    'Shaman’s Harvest',
    'Shaun White',
    'Shawn Wasabi',
    'Shey Baba',
    'Shlump',
    'Shvpes',
    'SICK INDIVIDUALS',
    'Sigrid',
    'Sikdope',
    'Silent Planet',
    'Silverstein',
    'Single Mothers',
    'Sir Michael Rocks',
    'Six60',
    'Siya',
    'The Skatalites',
    'Skepta',
    'Ski Mask the Slump God',
    'Skid Row',
    'Skinny Lister',
    'Skinnyfromthe9',
    'The Skints',
    'Skism',
    'Skyharbor',
    'SLANDER',
    'Slaughterhouse',
    'Slaves',
    'Sleep Token',
    'Sleeping With Sirens',
    'Slenderbodies',
    'Slothrust',
    'Smiler',
    'The Smith Street Band',
    'SMLE',
    "The Smoker's Club",
    'Snails',
    'Snarky Puppy',
    'Snoh Aalegra',
    'So You Think You Can Dance',
    'Sol',
    'Sol3 Mio',
    'Soleima',
    'Sombear',
    'SonReal',
    'Sons Of Bill',
    'Sophia Grace Brownlee',
    'Sophie Evans',
    'Sosupersam',
    'Soulection',
    'The Sounds',
    'Space Jesus',
    'SPACE LACES',
    'Spag Heddy',
    'Spock',
    'Squeeze',
    'Squnto',
    'Staind',
    'Stand Atlantic',
    'Starset',
    'State Radio',
    'Status Quo',
    'Steel Panther',
    'Stelartronic',
    'Stella Parton',
    'Steps',
    'Steve Earle',
    'Steve Harley & Cockney Rebel',
    'Steve James',
    'Steve Wozniak',
    'Steven Van Zandt',
    'Steven Wilson',
    'Stick to Your Guns',
    'Sticky Fingers',
    'Story Of The Year',
    'Stray From The Path',
    'Streetlight Manifesto',
    'Streetlight Manifesto',
    'Stromaé',
    'SubDocta',
    'Sublime with Rome',
    'Subtronics',
    'Suburban Living',
    'Suicidal Tendencies',
    'Sullivan King',
    'Sum 41',
    'The Summer Set',
    'Summer Slaughter Tour',
    'Summer Walker',
    'Sunn O)))',
    'Susanne Sundfør',
    'Svdden Death',
    'Swan Fyahbwoy',
    'Sweet Apple',
    'Swet Shop Boys',
    'Sylar',
    'T2',
    'The Tailormade',
    'Talos',
    'Tancred',
    'Tanya Tucker',
    'Tarrus Riley',
    'TASKA BLACK',
    'Tayler Buono',
    'Taylor Janzen',
    'Taylor McFerrin',
    'TC',
    'The Tea Party',
    'Teleman',
    'The Temptations Review feat. Dennis Edwards',
    'Tender Central',
    'Terri Clark',
    'Texas',
    'The Adelaides',
    'The Amazons',
    'The Beta Machine',
    'The Big Pink',
    'The Blancos',
    'The Bright Light Social Hour',
    'The Brummies',
    'The Commodores',
    'The Cool Kids',
    'The Damned',
    'The Driver Era',
    'The Jacksons',
    'The Jaded Hearts Club',
    'The Kingdom Choir',
    'The Original Misfits',
    'The Piano Guys',
    'The Soul Rebels',
    'The Sound Of Animals Fighting',
    'The Temperance Movement',
    'The Upbeats',
    'The World Is A Beautiful Place & I Am No Longer Afraid To Di',
    'Theory of a Deadman',
    'This Wild Life',
    'Thomas Dybdahl',
    'Thomas Wynn & The Believers',
    'Thunder',
    'Thursday',
    'Tierra Whack',
    'Tiger Drive',
    'Time for Three',
    'Times of Grace',
    'Timmy Trumpet',
    'Tina Guo',
    'Tinariwen',
    'Tiny Moving Parts',
    'Tisoki',
    'Tkay',
    'Toby Keith',
    'Todd Dorigo',
    'Todrick Hall',
    'Toh Kay',
    'Tokyo Machine',
    'Tom Morello: The Nightwatchman',
    'Tommy Newport',
    'Toni Braxton',
    'Tonight Alive',
    'Tony Allen',
    'Too Close To Touch',
    'Toots & The Maytals',
    'TOPS',
    'Tory Belleci',
    'Tosin Abasi',
    'Tove Styrke',
    'Trace Adkins',
    'The Tragically Hip',
    'Trailer Park Boys',
    'Trampa',
    'Trash Boat',
    'Treasure Fingers',
    'Tremonti',
    'Trevor Moran',
    'Trivium',
    'Tropical Fuck Storm',
    'TS7',
    'Turbowolf',
    'Turnstile',
    'Tyla Yaweh',
    'Tyler Bryant and The Shakedown',
    'Tyler Henry',
    'TYNAN',
    'UB40 featuring Ali Campbell, Astro and Mickey Virtue',
    'Ubur',
    'Um..',
    'Una Healy',
    'The Underachievers',
    'Underoath',
    'Underworld',
    'United Nations',
    'Until The Ribbon Breaks',
    'Urge Overkill',
    'US THE DUO',
    'The Used',
    'Vanessa Carlton',
    'Vanessa Paradis',
    'Vato Gonzalez',
    'Veil of Maya',
    'Vessels',
    'Vic Mensa',
    'Victory Boyd',
    'VINAI',
    'Vinnie Caruana',
    'Vintage Culture',
    'Violent SOHO',
    'Vita and the Woolf',
    'Vitalic',
    'VOIVOD',
    'Volac',
    'Wage War',
    'Walk Off The Earth',
    'Walker Lukens',
    'War',
    'Waterloo Revival',
    'Watermedown',
    'Watsky',
    'Wavedash',
    'Way Out West',
    'While She Sleeps',
    'WHIPPED CREAM',
    'The White Noise',
    'The Whooligan',
    "Why Don't We",
    'Wiki',
    'Wiley',
    'Wilkinson',
    'William Black',
    'William Singe',
    'WILSON',
    'With Confidence',
    'Witt Lowry',
    'Wiwek',
    'Woes',
    'Wolfies Just Fine',
    'The Wonder Years',
    'Wongo',
    'Woodkid',
    'Woody Allen and His New Orleans Jazz Band',
    'Wooli',
    'The Word Alive',
    'X Ambassadors',
    'XamVolo',
    'Xan Griffin',
    'Xie',
    'Xuitcasecity',
    'Y.O.U.N.G',
    'Yann Tiersen',
    'Yelle',
    'Yellow Claw',
    'YFN LUCCI',
    'YG',
    'Yo Gotti',
    'YOTA',
    'Young Guns',
    'Young Thug',
    'YoungBoy Never Broke Again',
    'Youngr',
    'Your Old Droog',
    'Zakk Sabbath',
    'Zakk Wylde',
    'Zeal & Ardor',
    'Zebrahead',
    'Zelooperz',
    'Zeshan B',
    'Zhavia',
    'Zimmer',
    'Zipper Club',
    'Zomboy'
  ]
};

export default artistsByAgency;
